### ISSUE TITLE
abudio btn - hand cursor

### ISSUE THREAD

**Issue by capricorn66** [dapphp/securimage#20]
any chance for adding hand cursor for audio btn?

**Comment by peterdd** [comment]
Seems only the swf fallback is effected in current version. So the flash swf must be changed/rewritten
Probably not worth the effort with better html5 audio support by browsers in 2016.
html5 audio has the pointer cursor on :hover.

**Comment by dapphp** [comment]
@peterdd Agreed.  I also plan on *removing* Flash fallback in the next version coming out in a month or so.  The only caveat of that is that no version of IE supports WAV in HTML5 audio (ironic since MS co-created WAV, but I get it, wav files are big and not mobile friendly) so I'll have to come up with another workaround for those who can't use LAME for wav to mp3 conversion.  I'll create a separate issue for that.
