### ISSUE TITLE
JS: copyElement() method doesn't exist

### ISSUE THREAD

**Issue by mlchevallier** [dapphp/securimage#51]
When I try to use the 3.6 version of Securimage on IE11, I've got the following JS error: copyElement() method doesn't exist. Indeed, I look into the securimage.js file, and the method is used but is not implemented. Maybe this is a JS core method, but it seems not to be understood my MSIE.
Could you please look into this?
Thanks a lot for your work.

**Comment by dapphp** [comment]
Hi,

Thanks for pointing this out.  Last minute there were some issues with the original copyElement method in native Android browsers so I had to rework it hence the renamed function and I missed it in the Flash fallback.

This is fixed in 3.6.1 which is now available on GitHub (just replace securimage.js with the newest one).  Files will be updated on phpcaptcha.org shortly as well.
