### ISSUE TITLE
The script tried to execute a method or access a property of an incomplete object

### ISSUE THREAD

**Issue by fr8ak2** [dapphp/securimage#68]
For nextgen branch.
Here is a screenshot http://prntscr.com/elz0cw.

Removed from example_form.php session_start() and it started working, because the Session Adapter already starting session, after this changes expiration time of captcha not working. 

I have searched for issue and couldn't resolve it. Maybe it should be added to get function in Session Adapter.

**Comment by dapphp** [comment]
Hi,

Thanks for the report.  Nextgen isn't quite ready for production, and for this the fix would probably be to autoload the Securimage classes in the example form prior to calling session_start, or remove that line as you mentioned since the SessionAdapter will start the session properly before any HTML output is generated.

I am using nextgen on some production sites and the WordPress plugin without issue, but I haven't gone through all the examples or completed documentation yet.

**Comment by fr8ak2** [comment]
Thanks for response. Only problem is expiry time of captcha. It doesn't react. I will try to autoload classes in form file.

**Comment by fr8ak2** [comment]
I tried, captcha worked, but expiry time non responding, it let me go throw anyway, if the time has expired.
