### ISSUE TITLE
PSR-4 Autoloader

### ISSUE THREAD

**Issue by ximex** [dapphp/securimage#80]
Make this lib compatible with the PSR-4 Autoloader standard
https://www.php-fig.org/psr/psr-4/

**Comment by jaisato** [comment]
I hope that this proposal will be supported.

**Comment by dapphp** [comment]
The nextgen branch / version 4.0 supports PSR-4 and would be the recommended version for any future development. This project will not be supported much longer so I would encourage forking for longer term needs. Due to widespread use in the current form I'm not sure master will see the PSR-4 and heavily refactored version that is in the 4.0 nextgen branch.

Thank you for your interest and comments.
